# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GeoQuiz' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GeoQuiz
  pod 'Toast-Swift', '~> 5.0.0'

  target 'GeoQuizTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GeoQuizUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
